### ISSUE TITLE
可以增加支持2.2版本吗

### ISSUE THREAD

**Issue by anhao** [friendsofhyperf/sentry#1]
可以增加支持2.2版本吗

**Comment by huangdijia** [comment]
不确定是否支持 PHP7.3，你试试看

`composer require friendsofhyperf/sentry:2.x-dev`

**Comment by anhao** [comment]
> 不确定是否支持 PHP7.3，你试试看
> 
> `composer require friendsofhyperf/sentry:2.x-dev`

好的谢谢,最新的2.2也是支持php8的

**Comment by anhao** [comment]
在启动项目时，LoggerAspect 里 $proceedingJoinPoint->arguments 获取数据会提示
 `PHP Warning:  Undefined array key "datetime" `

**Comment by huangdijia** [comment]
https://github.com/friendsofhyperf/components/pull/73
