### ISSUE TITLE
执行物化视图操作会有警告

### ISSUE THREAD

**Issue by laojinbao** [friendsofhyperf/sentry#8]
问题：
`Warning: Undefined array key 0 in /xxx/vendor/friendsofhyperf/sentry/src/Util/SqlParser.php on line 38`
原因：
PhpMyAdmin\SqlParser不支持PostgreSQL

**Comment by huangdijia** [comment]
@laojinbao 安装 dev 版本测试看看

```shell
composer require friendsofhyperf/sentry:3.1.x-dev
```

没问题我再发个版本

**Comment by laojinbao** [comment]
> @laojinbao 安装 dev 版本测试看看
> 
> ```shell
> composer require friendsofhyperf/sentry:3.1.x-dev
> ```
> 
> 没问题我再发个版本

没问题了
